require: rubocop-rails

Documentation:
  Enabled: false

AllCops:
 Exclude:
  - db/**/*
  - bin/**/*
  - config/**/*

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Metrics/BlockLength:
 Max: 50

Metrics/AbcSize:
  Enabled: false


Rails/HasManyOrHasOneDependent:
  Enabled: false

