databases:
  - name: postgres
    databaseName: shopify_app
    user: shopify_admin

services:
  - type: web
    name: shopify_app
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: ENV["SHOPIFY_APP_DATABASE_URL"]
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

# databases:
#   - name: mysite
#     databaseName: mysite
#     user: mysite

# services:
#   - type: web
#     name: mysite
#     runtime: ruby
#     buildCommand: "./bin/render-build.sh"
#     startCommand: "bundle exec puma -C config/puma.rb"
#     envVars:
#       - key: DATABASE_URL
#         fromDatabase:
#           name: mysite
#           property: connectionString
#       - key: RAILS_MASTER_KEY
#         sync: false